/**
 * tvQuran.com Modern Interface Data Store
 * Comprehensive dataset for 114 Surahs, 30+ World-Renowned Reciters,
 * Curated Special Collections, Live Radios & TV Streams, and Mushaf Text.
 */

const TVQURAN_DATA = {
  // All 114 Surahs with metadata
  surahs: [
    { id: 1, name_ar: "الفاتحة", name_en: "Al-Fatihah", translation_en: "The Opening", type: "Meccan", verses: 7, page: 1, juzz: 1 },
    { id: 2, name_ar: "البقرة", name_en: "Al-Baqarah", translation_en: "The Cow", type: "Medinan", verses: 286, page: 2, juzz: 1 },
    { id: 3, name_ar: "آل عمران", name_en: "Ali 'Imran", translation_en: "Family of Imran", type: "Medinan", verses: 200, page: 50, juzz: 3 },
    { id: 4, name_ar: "النساء", name_en: "An-Nisa", translation_en: "The Women", type: "Medinan", verses: 176, page: 77, juzz: 4 },
    { id: 5, name_ar: "المائدة", name_en: "Al-Ma'idah", translation_en: "The Table Spread", type: "Medinan", verses: 120, page: 106, juzz: 6 },
    { id: 6, name_ar: "الأنعام", name_en: "Al-An'am", translation_en: "The Cattle", type: "Meccan", verses: 165, page: 128, juzz: 7 },
    { id: 7, name_ar: "الأعراف", name_en: "Al-A'raf", translation_en: "The Heights", type: "Meccan", verses: 206, page: 151, juzz: 8 },
    { id: 8, name_ar: "الأنفال", name_en: "Al-Anfal", translation_en: "The Spoils of War", type: "Medinan", verses: 75, page: 177, juzz: 9 },
    { id: 9, name_ar: "التوبة", name_en: "At-Tawbah", translation_en: "The Repentance", type: "Medinan", verses: 129, page: 187, juzz: 10 },
    { id: 10, name_ar: "يونس", name_en: "Yunus", translation_en: "Jonah", type: "Meccan", verses: 109, page: 208, juzz: 11 },
    { id: 11, name_ar: "هود", name_en: "Hud", translation_en: "Hud", type: "Meccan", verses: 123, page: 221, juzz: 11 },
    { id: 12, name_ar: "يوسف", name_en: "Yusuf", translation_en: "Joseph", type: "Meccan", verses: 111, page: 235, juzz: 12 },
    { id: 13, name_ar: "الرعد", name_en: "Ar-Ra'd", translation_en: "The Thunder", type: "Medinan", verses: 43, page: 249, juzz: 13 },
    { id: 14, name_ar: "إبراهيم", name_en: "Ibrahim", translation_en: "Abraham", type: "Meccan", verses: 52, page: 255, juzz: 13 },
    { id: 15, name_ar: "الحجر", name_en: "Al-Hijr", translation_en: "The Rocky Tract", type: "Meccan", verses: 99, page: 262, juzz: 14 },
    { id: 16, name_ar: "النحل", name_en: "An-Nahl", translation_en: "The Bee", type: "Meccan", verses: 128, page: 267, juzz: 14 },
    { id: 17, name_ar: "الإسراء", name_en: "Al-Isra", translation_en: "The Night Journey", type: "Meccan", verses: 111, page: 282, juzz: 15 },
    { id: 18, name_ar: "الكهف", name_en: "Al-Kahf", translation_en: "The Cave", type: "Meccan", verses: 110, page: 293, juzz: 15 },
    { id: 19, name_ar: "مريم", name_en: "Maryam", translation_en: "Mary", type: "Meccan", verses: 98, page: 305, juzz: 16 },
    { id: 20, name_ar: "طه", name_en: "Taha", translation_en: "Ta-Ha", type: "Meccan", verses: 135, page: 312, juzz: 16 },
    { id: 21, name_ar: "الأنبياء", name_en: "Al-Anbiya", translation_en: "The Prophets", type: "Meccan", verses: 112, page: 322, juzz: 17 },
    { id: 22, name_ar: "الحج", name_en: "Al-Hajj", translation_en: "The Pilgrimage", type: "Medinan", verses: 78, page: 332, juzz: 17 },
    { id: 23, name_ar: "المؤمنون", name_en: "Al-Mu'minun", translation_en: "The Believers", type: "Meccan", verses: 118, page: 342, juzz: 18 },
    { id: 24, name_ar: "النور", name_en: "An-Nur", translation_en: "The Light", type: "Medinan", verses: 64, page: 350, juzz: 18 },
    { id: 25, name_ar: "الفرقان", name_en: "Al-Furqan", translation_en: "The Criterion", type: "Meccan", verses: 77, page: 359, juzz: 18 },
    { id: 26, name_ar: "الشعراء", name_en: "Ash-Shu'ara", translation_en: "The Poets", type: "Meccan", verses: 227, page: 367, juzz: 19 },
    { id: 27, name_ar: "النمل", name_en: "An-Naml", translation_en: "The Ant", type: "Meccan", verses: 93, page: 377, juzz: 19 },
    { id: 28, name_ar: "القصص", name_en: "Al-Qasas", translation_en: "The Stories", type: "Meccan", verses: 88, page: 385, juzz: 20 },
    { id: 29, name_ar: "العنكبوت", name_en: "Al-'Ankabut", translation_en: "The Spider", type: "Meccan", verses: 69, page: 396, juzz: 20 },
    { id: 30, name_ar: "الروم", name_en: "Ar-Rum", translation_en: "The Romans", type: "Meccan", verses: 60, page: 404, juzz: 21 },
    { id: 31, name_ar: "لقمان", name_en: "Luqman", translation_en: "Luqman", type: "Meccan", verses: 34, page: 411, juzz: 21 },
    { id: 32, name_ar: "السجدة", name_en: "As-Sajdah", translation_en: "The Prostration", type: "Meccan", verses: 30, page: 415, juzz: 21 },
    { id: 33, name_ar: "الأحزاب", name_en: "Al-Ahzab", translation_en: "The Combined Forces", type: "Medinan", verses: 73, page: 418, juzz: 21 },
    { id: 34, name_ar: "سبأ", name_en: "Saba", translation_en: "Sheba", type: "Meccan", verses: 54, page: 428, juzz: 22 },
    { id: 35, name_ar: "فاطر", name_en: "Fatir", translation_en: "Originator", type: "Meccan", verses: 45, page: 434, juzz: 22 },
    { id: 36, name_ar: "يس", name_en: "Ya-Sin", translation_en: "Ya-Sin", type: "Meccan", verses: 83, page: 440, juzz: 22 },
    { id: 37, name_ar: "الصافات", name_en: "As-Saffat", translation_en: "Those who set the Ranks", type: "Meccan", verses: 182, page: 446, juzz: 23 },
    { id: 38, name_ar: "ص", name_en: "Sad", translation_en: "The Letter Sad", type: "Meccan", verses: 88, page: 453, juzz: 23 },
    { id: 39, name_ar: "الزمر", name_en: "Az-Zumar", translation_en: "The Troops", type: "Meccan", verses: 75, page: 458, juzz: 23 },
    { id: 40, name_ar: "غافر", name_en: "Ghafir", translation_en: "The Forgiver", type: "Meccan", verses: 85, page: 467, juzz: 24 },
    { id: 41, name_ar: "فصلت", name_en: "Fussilat", translation_en: "Explained in Detail", type: "Meccan", verses: 54, page: 477, juzz: 24 },
    { id: 42, name_ar: "الشورى", name_en: "Ash-Shuraa", translation_en: "The Consultation", type: "Meccan", verses: 53, page: 483, juzz: 25 },
    { id: 43, name_ar: "الزخرف", name_en: "Az-Zukhruf", translation_en: "The Ornaments of Gold", type: "Meccan", verses: 89, page: 489, juzz: 25 },
    { id: 44, name_ar: "الدخان", name_en: "Ad-Dukhan", translation_en: "The Smoke", type: "Meccan", verses: 59, page: 496, juzz: 25 },
    { id: 45, name_ar: "الجاثية", name_en: "Al-Jathiyah", translation_en: "The Crouching", type: "Meccan", verses: 37, page: 499, juzz: 25 },
    { id: 46, name_ar: "الأحقاف", name_en: "Al-Ahqaf", translation_en: "The Wind-Curved Sandhills", type: "Meccan", verses: 35, page: 502, juzz: 26 },
    { id: 47, name_ar: "محمد", name_en: "Muhammad", translation_en: "Muhammad", type: "Medinan", verses: 38, page: 507, juzz: 26 },
    { id: 48, name_ar: "الفتح", name_en: "Al-Fath", translation_en: "The Victory", type: "Medinan", verses: 29, page: 511, juzz: 26 },
    { id: 49, name_ar: "الحجرات", name_en: "Al-Hujurat", translation_en: "The Rooms", type: "Medinan", verses: 18, page: 515, juzz: 26 },
    { id: 50, name_ar: "ق", name_en: "Qaf", translation_en: "The Letter Qaf", type: "Meccan", verses: 45, page: 518, juzz: 26 },
    { id: 51, name_ar: "الذاريات", name_en: "Adh-Dhariyat", translation_en: "The Winnowing Winds", type: "Meccan", verses: 60, page: 520, juzz: 26 },
    { id: 52, name_ar: "الطور", name_en: "At-Tur", translation_en: "The Mount", type: "Meccan", verses: 49, page: 523, juzz: 27 },
    { id: 53, name_ar: "النجم", name_en: "An-Najm", translation_en: "The Star", type: "Meccan", verses: 62, page: 526, juzz: 27 },
    { id: 54, name_ar: "القمر", name_en: "Al-Qamar", translation_en: "The Moon", type: "Meccan", verses: 55, page: 528, juzz: 27 },
    { id: 55, name_ar: "الرحمن", name_en: "Ar-Rahman", translation_en: "The Beneficent", type: "Medinan", verses: 78, page: 531, juzz: 27 },
    { id: 56, name_ar: "الواقعة", name_en: "Al-Waqi'ah", translation_en: "The Inevitable", type: "Meccan", verses: 96, page: 534, juzz: 27 },
    { id: 57, name_ar: "الحديد", name_en: "Al-Hadid", translation_en: "The Iron", type: "Medinan", verses: 29, page: 537, juzz: 27 },
    { id: 58, name_ar: "المجادلة", name_en: "Al-Mujadila", translation_en: "The Pleading Woman", type: "Medinan", verses: 22, page: 542, juzz: 28 },
    { id: 59, name_ar: "الحشر", name_en: "Al-Hashr", translation_en: "The Exile", type: "Medinan", verses: 24, page: 545, juzz: 28 },
    { id: 60, name_ar: "الممتحنة", name_en: "Al-Mumtahanah", translation_en: "She that is to be examined", type: "Medinan", verses: 13, page: 549, juzz: 28 },
    { id: 61, name_ar: "الصف", name_en: "As-Saf", translation_en: "The Ranks", type: "Medinan", verses: 14, page: 551, juzz: 28 },
    { id: 62, name_ar: "الجمعة", name_en: "Al-Jumu'ah", translation_en: "The Congregation, Friday", type: "Medinan", verses: 11, page: 553, juzz: 28 },
    { id: 63, name_ar: "المنافقون", name_en: "Al-Munafiqun", translation_en: "The Hypocrites", type: "Medinan", verses: 11, page: 554, juzz: 28 },
    { id: 64, name_ar: "التغابن", name_en: "At-Taghabun", translation_en: "The Mutual Disillusion", type: "Medinan", verses: 18, page: 556, juzz: 28 },
    { id: 65, name_ar: "الطلاق", name_en: "At-Talaq", translation_en: "The Divorce", type: "Medinan", verses: 12, page: 558, juzz: 28 },
    { id: 66, name_ar: "التحريم", name_en: "At-Tahrim", translation_en: "The Prohibition", type: "Medinan", verses: 12, page: 560, juzz: 28 },
    { id: 67, name_ar: "الملك", name_en: "Al-Mulk", translation_en: "The Sovereignty", type: "Meccan", verses: 30, page: 562, juzz: 29 },
    { id: 68, name_ar: "القلم", name_en: "Al-Qalam", translation_en: "The Pen", type: "Meccan", verses: 52, page: 564, juzz: 29 },
    { id: 69, name_ar: "الحاقة", name_en: "Al-Haqqah", translation_en: "The Reality", type: "Meccan", verses: 52, page: 566, juzz: 29 },
    { id: 70, name_ar: "المعارج", name_en: "Al-Ma'arij", translation_en: "The Ascending Stairways", type: "Meccan", verses: 44, page: 568, juzz: 29 },
    { id: 71, name_ar: "نوح", name_en: "Nuh", translation_en: "Noah", type: "Meccan", verses: 28, page: 570, juzz: 29 },
    { id: 72, name_ar: "الجن", name_en: "Al-Jinn", translation_en: "The Jinn", type: "Meccan", verses: 28, page: 572, juzz: 29 },
    { id: 73, name_ar: "المزمل", name_en: "Al-Muzzammil", translation_en: "The Enshrouded One", type: "Meccan", verses: 20, page: 574, juzz: 29 },
    { id: 74, name_ar: "المدثر", name_en: "Al-Muddaththir", translation_en: "The Cloaked One", type: "Meccan", verses: 56, page: 575, juzz: 29 },
    { id: 75, name_ar: "القيامة", name_en: "Al-Qiyamah", translation_en: "The Resurrection", type: "Meccan", verses: 40, page: 577, juzz: 29 },
    { id: 76, name_ar: "الإنسان", name_en: "Al-Insan", translation_en: "The Man", type: "Medinan", verses: 31, page: 578, juzz: 29 },
    { id: 77, name_ar: "المرسلات", name_en: "Al-Mursalat", translation_en: "The Emissaries", type: "Meccan", verses: 50, page: 580, juzz: 29 },
    { id: 78, name_ar: "النبأ", name_en: "An-Naba", translation_en: "The Tidings", type: "Meccan", verses: 40, page: 582, juzz: 30 },
    { id: 79, name_ar: "النازعات", name_en: "An-Nazi'at", translation_en: "Those who drag forth", type: "Meccan", verses: 46, page: 583, juzz: 30 },
    { id: 80, name_ar: "عبس", name_en: "'Abasa", translation_en: "He Frowned", type: "Meccan", verses: 42, page: 585, juzz: 30 },
    { id: 81, name_ar: "التكوير", name_en: "At-Takwir", translation_en: "The Overthrowing", type: "Meccan", verses: 29, page: 586, juzz: 30 },
    { id: 82, name_ar: "الانفطار", name_en: "Al-Infitar", translation_en: "The Cleaving", type: "Meccan", verses: 19, page: 587, juzz: 30 },
    { id: 83, name_ar: "المطففين", name_en: "Al-Mutaffifin", translation_en: "The Defrauding", type: "Meccan", verses: 36, page: 587, juzz: 30 },
    { id: 84, name_ar: "الانشقاق", name_en: "Al-Inshiqaq", translation_en: "The Splitting Open", type: "Meccan", verses: 25, page: 589, juzz: 30 },
    { id: 85, name_ar: "البروج", name_en: "Al-Buruj", translation_en: "The Mansions of the Stars", type: "Meccan", verses: 22, page: 590, juzz: 30 },
    { id: 86, name_ar: "الطارق", name_en: "At-Tariq", translation_en: "The Morning Star", type: "Meccan", verses: 17, page: 591, juzz: 30 },
    { id: 87, name_ar: "الأعلى", name_en: "Al-A'la", translation_en: "The Most High", type: "Meccan", verses: 19, page: 591, juzz: 30 },
    { id: 88, name_ar: "الغاشية", name_en: "Al-Ghashiyah", translation_en: "The Overwhelming", type: "Meccan", verses: 26, page: 592, juzz: 30 },
    { id: 89, name_ar: "الفجر", name_en: "Al-Fajr", translation_en: "The Dawn", type: "Meccan", verses: 30, page: 593, juzz: 30 },
    { id: 90, name_ar: "البلد", name_en: "Al-Balad", translation_en: "The City", type: "Meccan", verses: 20, page: 594, juzz: 30 },
    { id: 91, name_ar: "الشمس", name_en: "Ash-Shams", translation_en: "The Sun", type: "Meccan", verses: 15, page: 595, juzz: 30 },
    { id: 92, name_ar: "الليل", name_en: "Al-Layl", translation_en: "The Night", type: "Meccan", verses: 21, page: 595, juzz: 30 },
    { id: 93, name_ar: "الضحى", name_en: "Ad-Duhaa", translation_en: "The Morning Hours", type: "Meccan", verses: 11, page: 596, juzz: 30 },
    { id: 94, name_ar: "الشرح", name_en: "Ash-Sharh", translation_en: "The Relief", type: "Meccan", verses: 8, page: 596, juzz: 30 },
    { id: 95, name_ar: "التين", name_en: "At-Tin", translation_en: "The Fig", type: "Meccan", verses: 8, page: 597, juzz: 30 },
    { id: 96, name_ar: "العلق", name_en: "Al-'Alaq", translation_en: "The Clot", type: "Meccan", verses: 19, page: 597, juzz: 30 },
    { id: 97, name_ar: "القدر", name_en: "Al-Qadr", translation_en: "The Power, Fate", type: "Meccan", verses: 5, page: 598, juzz: 30 },
    { id: 98, name_ar: "البينة", name_en: "Al-Bayyinah", translation_en: "The Clear Proof", type: "Medinan", verses: 8, page: 598, juzz: 30 },
    { id: 99, name_ar: "الزلزلة", name_en: "Az-Zalzalah", translation_en: "The Earthquake", type: "Medinan", verses: 8, page: 599, juzz: 30 },
    { id: 100, name_ar: "العاديات", name_en: "Al-'Adiyat", translation_en: "The Courser", type: "Meccan", verses: 11, page: 599, juzz: 30 },
    { id: 101, name_ar: "القارعة", name_en: "Al-Qari'ah", translation_en: "The Calamity", type: "Meccan", verses: 11, page: 600, juzz: 30 },
    { id: 102, name_ar: "التكاثر", name_en: "At-Takathur", translation_en: "The Rivalry in world increase", type: "Meccan", verses: 8, page: 600, juzz: 30 },
    { id: 103, name_ar: "العصر", name_en: "Al-'Asr", translation_en: "The Declining Day, Epoch", type: "Meccan", verses: 3, page: 601, juzz: 30 },
    { id: 104, name_ar: "الهمزة", name_en: "Al-Humazah", translation_en: "The Traducer", type: "Meccan", verses: 9, page: 601, juzz: 30 },
    { id: 105, name_ar: "الفيل", name_en: "Al-Fil", translation_en: "The Elephant", type: "Meccan", verses: 5, page: 601, juzz: 30 },
    { id: 106, name_ar: "قريش", name_en: "Quraysh", translation_en: "Quraysh", type: "Meccan", verses: 4, page: 602, juzz: 30 },
    { id: 107, name_ar: "الماعون", name_en: "Al-Ma'un", translation_en: "The Small Kindness", type: "Meccan", verses: 7, page: 602, juzz: 30 },
    { id: 108, name_ar: "الكوثر", name_en: "Al-Kawthar", translation_en: "The Abundance", type: "Meccan", verses: 3, page: 602, juzz: 30 },
    { id: 109, name_ar: "الكافرون", name_en: "Al-Kafirun", translation_en: "The Disbelievers", type: "Meccan", verses: 6, page: 603, juzz: 30 },
    { id: 110, name_ar: "النصر", name_en: "An-Nasr", translation_en: "The Divine Support", type: "Medinan", verses: 3, page: 603, juzz: 30 },
    { id: 111, name_ar: "المسد", name_en: "Al-Masad", translation_en: "The Palm Fibre", type: "Meccan", verses: 5, page: 603, juzz: 30 },
    { id: 112, name_ar: "الإخلاص", name_en: "Al-Ikhlas", translation_en: "The Sincerity", type: "Meccan", verses: 4, page: 604, juzz: 30 },
    { id: 113, name_ar: "الفلق", name_en: "Al-Falaq", translation_en: "The Daybreak", type: "Meccan", verses: 5, page: 604, juzz: 30 },
    { id: 114, name_ar: "الناس", name_en: "An-Nas", translation_en: "Mankind", type: "Meccan", verses: 6, page: 604, juzz: 30 }
  ],

  // 30+ World-Renowned Reciters with high-speed CDN streaming endpoints
  reciters: [
    {
      id: "alafasy",
      name_ar: "مشاري راشد العفاسي",
      name_en: "Mishary Rashid Alafasy",
      letter: "M",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server8.mp3quran.net/afs/",
      avatar: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=300&auto=format&fit=crop&q=80",
      color: "#059669",
      total_recitations: 114,
      total_listens: "48.5M",
      country: "Kuwait",
      bio_en: "Imam of the Grand Mosque of Kuwait and internationally acclaimed reciter and nasheed artist.",
      bio_ar: "إمام المسجد الكبير بدولة الكويت وأحد أشهر قراء العالم الإسلامي المعاصرين."
    },
    {
      id: "abdulbasit-murattal",
      name_ar: "عبد الباسط عبد الصمد (مرتل)",
      name_en: "Abdul Basit Abdul Samad (Murattal)",
      letter: "A",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server7.mp3quran.net/basit/",
      avatar: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=300&auto=format&fit=crop&q=80",
      color: "#D97706",
      total_recitations: 114,
      total_listens: "62.1M",
      country: "Egypt",
      bio_en: "Legendary Egyptian Qari known as 'The Golden Throat' and the Voice of Mecca.",
      bio_ar: "صاحب الحنجرة الذهبية وصوت مكة، أحد أعظم قراء القرآن في التاريخ الحديث."
    },
    {
      id: "abdulbasit-mujawwad",
      name_ar: "عبد الباسط عبد الصمد (مجود)",
      name_en: "Abdul Basit Abdul Samad (Mujawwad)",
      letter: "A",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server7.mp3quran.net/basit/Almusshaf-Al-Mojawwad/",
      avatar: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=300&auto=format&fit=crop&q=80",
      color: "#B45309",
      total_recitations: 114,
      total_listens: "39.4M",
      country: "Egypt",
      bio_en: "Masterful melodic recitation (Mujawwad) by Sheikh Abdul Basit Abdul Samad.",
      bio_ar: "المصحف المجود الخالد للشيخ عبد الباسط عبد الصمد."
    },
    {
      id: "sudais",
      name_ar: "عبد الرحمن السديس",
      name_en: "Abdul Rahman Al-Sudais",
      letter: "A",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server11.mp3quran.net/sds/",
      avatar: "https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=300&auto=format&fit=crop&q=80",
      color: "#10B981",
      total_recitations: 114,
      total_listens: "44.2M",
      country: "Saudi Arabia",
      bio_en: "Chief Imam and Khatib of the Grand Mosque in Makkah, Saudi Arabia.",
      bio_ar: "إمام وخطيب المسجد الحرام بمكة المكرمة والرئيس العام لشؤون المسجد الحرام."
    },
    {
      id: "shuraim",
      name_ar: "سعود الشريم",
      name_en: "Saud Al-Shuraim",
      letter: "S",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server7.mp3quran.net/shur/",
      avatar: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=300&auto=format&fit=crop&q=80",
      color: "#047857",
      total_recitations: 114,
      total_listens: "35.8M",
      country: "Saudi Arabia",
      bio_en: "Former leading Imam and Khatib of the Grand Mosque in Makkah.",
      bio_ar: "إمام وخطيب المسجد الحرام الأسبق وأستاذ الدراسات الإسلامية."
    },
    {
      id: "ghamdi",
      name_ar: "سعد الغامدي",
      name_en: "Saad Al-Ghamdi",
      letter: "S",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server7.mp3quran.net/s_gmd/",
      avatar: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=300&auto=format&fit=crop&q=80",
      color: "#3B82F6",
      total_recitations: 114,
      total_listens: "38.9M",
      country: "Saudi Arabia",
      bio_en: "Prominent Saudi reciter celebrated for smooth, melodious, and tranquil recitation.",
      bio_ar: "قارئ سعودي مشهور بصوته العذب وتلاوته الخاشعة الهادئة."
    },
    {
      id: "muaiqly",
      name_ar: "ماهر المعيقلي",
      name_en: "Maher Al-Muaiqly",
      letter: "M",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server12.mp3quran.net/maher/",
      avatar: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=300&auto=format&fit=crop&q=80",
      color: "#8B5CF6",
      total_recitations: 114,
      total_listens: "53.7M",
      country: "Saudi Arabia",
      bio_en: "Beloved Imam of the Grand Mosque in Makkah, famous for deeply emotional recitations.",
      bio_ar: "إمام المسجد الحرام بمكة المكرمة وصاحب التلاوات الباكية الخاشعة."
    },
    {
      id: "hussary-murattal",
      name_ar: "محمود خليل الحصري (مرتل)",
      name_en: "Mahmoud Khalil Al-Hussary",
      letter: "M",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server13.mp3quran.net/husr/",
      avatar: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=300&auto=format&fit=crop&q=80",
      color: "#6366F1",
      total_recitations: 114,
      total_listens: "41.6M",
      country: "Egypt",
      bio_en: "Master of Tajweed rules and pioneer of recorded Quranic recitations.",
      bio_ar: "شيخ عموم المقارئ المصرية الأسبق وشيخ علم التجويد الأول."
    },
    {
      id: "hussary-warsh",
      name_ar: "محمود خليل الحصري (ورش)",
      name_en: "Mahmoud Khalil Al-Hussary (Warsh)",
      letter: "M",
      riwayah_ar: "ورش عن نافع",
      riwayah_en: "Warsh 'an Nafi'",
      server_url: "https://server13.mp3quran.net/husr/warsh/",
      avatar: "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=300&auto=format&fit=crop&q=80",
      color: "#4F46E5",
      total_recitations: 114,
      total_listens: "19.8M",
      country: "Egypt",
      bio_en: "Flawless recitation according to the narration of Warsh 'an Nafi'.",
      bio_ar: "تلاوة متقنة برواية ورش عن نافع من طريق الأزرق."
    },
    {
      id: "dosari",
      name_ar: "ياسر الدوسري",
      name_en: "Yasser Al-Dosari",
      letter: "Y",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server11.mp3quran.net/yasser/",
      avatar: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=300&auto=format&fit=crop&q=80",
      color: "#EC4899",
      total_recitations: 114,
      total_listens: "47.9M",
      country: "Saudi Arabia",
      bio_en: "Imam of the Grand Mosque in Makkah known for captivating, powerful Quranic delivery.",
      bio_ar: "إمام المسجد الحرام بمكة المكرمة وعضو هيئة التدريس بجامعة الملك سعود."
    },
    {
      id: "minshawi-murattal",
      name_ar: "محمد صديق المنشاوي (مرتل)",
      name_en: "Mohamed Siddiq El-Minshawi",
      letter: "M",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server10.mp3quran.net/minsh/",
      avatar: "https://images.unsplash.com/photo-1513002749550-c59d786b8e6c?w=300&auto=format&fit=crop&q=80",
      color: "#F59E0B",
      total_recitations: 114,
      total_listens: "58.3M",
      country: "Egypt",
      bio_en: "Renowned as 'The Weeping Voice', an iconic master of emotive Quranic recitation.",
      bio_ar: "الصوت الباكي ذو النبرة الخاشعة الحزينة التي تهز القلوب."
    },
    {
      id: "minshawi-mujawwad",
      name_ar: "محمد صديق المنشاوي (مجود)",
      name_en: "Mohamed Siddiq El-Minshawi (Mujawwad)",
      letter: "M",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/",
      avatar: "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=300&auto=format&fit=crop&q=80",
      color: "#D97706",
      total_recitations: 114,
      total_listens: "36.2M",
      country: "Egypt",
      bio_en: "Sublime Mujawwad master recordings by Sheikh Mohamed Siddiq El-Minshawi.",
      bio_ar: "المصحف المجود الفريد للشيخ محمد صديق المنشاوي."
    },
    {
      id: "salmi",
      name_ar: "منصور السالمي",
      name_en: "Mansour Al-Salmi",
      letter: "M",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server14.mp3quran.net/mansor/",
      avatar: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=300&auto=format&fit=crop&q=80",
      color: "#14B8A6",
      total_recitations: 45,
      total_listens: "31.4M",
      country: "Saudi Arabia",
      bio_en: "Popular contemporary Islamic preacher and reciter with heart-touching tones.",
      bio_ar: "داعية وقارئ سعودي معاصر اشتهر بتلاواته المؤثرة وكلماته الوعظية."
    },
    {
      id: "khalid-jalil",
      name_ar: "خالد الجليل",
      name_en: "Khalid Al-Jalil",
      letter: "K",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server10.mp3quran.net/jleel/",
      avatar: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=300&auto=format&fit=crop&q=80",
      color: "#06B6D4",
      total_recitations: 86,
      total_listens: "29.7M",
      country: "Saudi Arabia",
      bio_en: "Imam of King Khalid Mosque in Riyadh, famous for deep poignant Surah recitations.",
      bio_ar: "إمام جامع الملك خالد بالرياض وصاحب التلاوات الخاشعة الشهيرة كسورة ق."
    },
    {
      id: "islam-sobhi",
      name_ar: "إسلام صبحي",
      name_en: "Islam Sobhi",
      letter: "I",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server14.mp3quran.net/islam/Rewayat-Hafs-A-n-Assem/",
      avatar: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=300&auto=format&fit=crop&q=80",
      color: "#6366F1",
      total_recitations: 60,
      total_listens: "34.6M",
      country: "Egypt",
      bio_en: "Young Egyptian reciter whose soothing and resonant style went viral globally.",
      bio_ar: "قارئ مصري شاب يتميز بصوت شجي وعذب لاقى شهرة واسعة."
    },
    {
      id: "hazza-balushi",
      name_ar: "هزاع البلوشي",
      name_en: "Hazza Al-Balushi",
      letter: "H",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server11.mp3quran.net/hazza/",
      avatar: "https://images.unsplash.com/photo-1491555103944-7c647fd857e6?w=300&auto=format&fit=crop&q=80",
      color: "#0284C7",
      total_recitations: 70,
      total_listens: "24.1M",
      country: "Oman",
      bio_en: "Omani reciter renowned for exceptionally soothing and calm recitation style.",
      bio_ar: "قارئ عماني يتميز بصوت رقيق ونبرة هادئة تريح النفوس."
    },
    {
      id: "raad-kurdi",
      name_ar: "رعد الكردي",
      name_en: "Raad Al-Kurdi",
      letter: "R",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server12.mp3quran.net/raad/",
      avatar: "https://images.unsplash.com/photo-1511497584788-87676104235f?w=300&auto=format&fit=crop&q=80",
      color: "#9333EA",
      total_recitations: 65,
      total_listens: "27.8M",
      country: "Iraq",
      bio_en: "Kurdish-Iraqi Imam and reciter with unique vocal richness and serenity.",
      bio_ar: "إمام وقارئ عراقي ذو صوت رخيم وأسلوب فريد في الترتيل."
    },
    {
      id: "idris-abkar",
      name_ar: "إدريس أبكر",
      name_en: "Idris Abkar",
      letter: "I",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server6.mp3quran.net/abkr/",
      avatar: "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=300&auto=format&fit=crop&q=80",
      color: "#10B981",
      total_recitations: 114,
      total_listens: "30.5M",
      country: "Saudi Arabia",
      bio_en: "Imam of Sheikh Zayed Grand Mosque, known for spiritual Duas and recitations.",
      bio_ar: "إمام جامع الشيخ زايد الكبير بأبوظبي وصاحب الأدعية والتلاوات الخاشعة."
    },
    {
      id: "ajamy",
      name_ar: "أحمد بن علي العجمي",
      name_en: "Ahmed Al-Ajamy",
      letter: "A",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server10.mp3quran.net/ajm/",
      avatar: "https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?w=300&auto=format&fit=crop&q=80",
      color: "#F97316",
      total_recitations: 114,
      total_listens: "42.3M",
      country: "Saudi Arabia",
      bio_en: "Prominent Saudi reciter with high-energy resonant vocal timbre.",
      bio_ar: "قارئ سعودي بارز مشهور بقوة صوته وصفائه وانتشار تسجيلاته عالمياً."
    },
    {
      id: "shatri",
      name_ar: "أبو بكر الشاطري",
      name_en: "Abu Bakr Al-Shatri",
      letter: "A",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server11.mp3quran.net/shatri/",
      avatar: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=300&auto=format&fit=crop&q=80",
      color: "#10B981",
      total_recitations: 114,
      total_listens: "33.2M",
      country: "Saudi Arabia",
      bio_en: "Esteemed Jeddah-based reciter recognized for serene and crystal-clear pronunciation.",
      bio_ar: "قارئ سعودي متميز بصوته الرخيم وإتقانه لمخارج الحروف والتجويد."
    },
    {
      id: "ali-jaber",
      name_ar: "علي جابر",
      name_en: "Ali Jaber",
      letter: "A",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server11.mp3quran.net/a_jbr/",
      avatar: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=300&auto=format&fit=crop&q=80",
      color: "#059669",
      total_recitations: 114,
      total_listens: "28.6M",
      country: "Saudi Arabia",
      bio_en: "Former Imam of the Grand Mosque in Makkah whose soulful voice inspired generations.",
      bio_ar: "إمام المسجد الحرام بمكة المكرمة الأسبق، صاحب الصوت الندي المؤثر."
    },
    {
      id: "mustafa-ismail",
      name_ar: "مصطفى إسماعيل",
      name_en: "Mustafa Ismail",
      letter: "M",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server8.mp3quran.net/mustafa/",
      avatar: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=300&auto=format&fit=crop&q=80",
      color: "#D97706",
      total_recitations: 114,
      total_listens: "26.4M",
      country: "Egypt",
      bio_en: "Unrivaled master of Maqamat melodic modes in Quranic recitation history.",
      bio_ar: "عبقري التلاوة وأستاذ المقامات القرآنية بلا منازع في مصر والعالم."
    },
    {
      id: "abdulrahman-mosad",
      name_ar: "عبد الرحمن مسعد",
      name_en: "Abdulrahman Mosad",
      letter: "A",
      riwayah_ar: "حفص عن عاصم",
      riwayah_en: "Hafs 'an Asim",
      server_url: "https://server16.mp3quran.net/abdulrahman_mossad/Rewayat-Hafs-A-n-Assem/",
      avatar: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=300&auto=format&fit=crop&q=80",
      color: "#0D9488",
      total_recitations: 40,
      total_listens: "22.3M",
      country: "Egypt",
      bio_en: "Acclaimed contemporary reciter known for serene low-pitch pacing.",
      bio_ar: "قارئ معاصر ذو نبرة صوت هادئة ومريحة تلقى رواجاً هائلاً."
    },
    {
      id: "yassin-al-jazairi",
      name_ar: "ياسين الجزائري",
      name_en: "Yassin Al-Jazairi",
      letter: "Y",
      riwayah_ar: "ورش عن نافع",
      riwayah_en: "Warsh 'an Nafi'",
      server_url: "https://server11.mp3quran.net/jaza/Rewayat-Warsh-A-n-Nafi-/",
      avatar: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=300&auto=format&fit=crop&q=80",
      color: "#2563EB",
      total_recitations: 114,
      total_listens: "16.7M",
      country: "Algeria",
      bio_en: "Celebrated Algerian reciter mastering the Warsh 'an Nafi' narration.",
      bio_ar: "قارئ جزائري متميز في تلاوة القرآن الكريم برواية ورش عن نافع."
    }
  ],

  // Curated Featured Collections (tvQuran Selections)
  collections: [
    {
      id: "emotional-recitations",
      category: "beautiful",
      title_ar: "تلاوات خاشعة ومؤثرة",
      title_en: "Heart-Touching Recitations",
      badge_ar: "الأكثر استماعاً",
      badge_en: "Trending",
      icon: "fa-heart",
      color: "#EC4899",
      description_ar: "مجموعة منتقاة بعناية من أروع التلاوات الخاشعة التي تقشعر لها الأبدان وتطمئن بها القلوب.",
      description_en: "A handpicked selection of deeply emotional and tranquil Quranic recitations.",
      tracks: [
        {
          id: "emo-1",
          title_ar: "سورة ق [16-35] - خالد الجليل",
          title_en: "Surah Qaf [16-35] - Khalid Al-Jalil",
          reciter_ar: "خالد الجليل",
          reciter_en: "Khalid Al-Jalil",
          surah_id: 50,
          duration: "06:42",
          listens: "6,211,400",
          url: "https://server10.mp3quran.net/jleel/050.mp3"
        },
        {
          id: "emo-2",
          title_ar: "سورة النمل [59-65] - منصور السالمي",
          title_en: "Surah An-Naml [59-65] - Mansour Al-Salmi",
          reciter_ar: "منصور السالمي",
          reciter_en: "Mansour Al-Salmi",
          surah_id: 27,
          duration: "05:18",
          listens: "4,820,300",
          url: "https://server14.mp3quran.net/mansor/027.mp3"
        },
        {
          id: "emo-3",
          title_ar: "سورة الفرقان [63-77] - ياسر الدوسري",
          title_en: "Surah Al-Furqan [63-77] - Yasser Al-Dosari",
          reciter_ar: "ياسر الدوسري",
          reciter_en: "Yasser Al-Dosari",
          surah_id: 25,
          duration: "07:35",
          listens: "5,110,800",
          url: "https://server11.mp3quran.net/yasser/025.mp3"
        },
        {
          id: "emo-4",
          title_ar: "سورة الرحمن - إسلام صبحي",
          title_en: "Surah Ar-Rahman - Islam Sobhi",
          reciter_ar: "إسلام صبحي",
          reciter_en: "Islam Sobhi",
          surah_id: 55,
          duration: "11:20",
          listens: "7,350,900",
          url: "https://server14.mp3quran.net/islam/Rewayat-Hafs-A-n-Assem/055.mp3"
        },
        {
          id: "emo-5",
          title_ar: "سورة الكهف - هزاع البلوشي",
          title_en: "Surah Al-Kahf - Hazza Al-Balushi",
          reciter_ar: "هزاع البلوشي",
          reciter_en: "Hazza Al-Balushi",
          surah_id: 18,
          duration: "24:15",
          listens: "3,940,200",
          url: "https://server11.mp3quran.net/hazza/018.mp3"
        }
      ]
    },
    {
      id: "ruqyah",
      category: "ruqyah",
      title_ar: "الرقية الشرعية",
      title_en: "Sharia Ruqyah",
      badge_ar: "شفاء وتحصين",
      badge_en: "Healing",
      icon: "fa-shield",
      color: "#10B981",
      description_ar: "الرقية الشرعية الشاملة من الكتاب والسنة لعلاج السحر والمس والعين والحسد والتحصين اليومي.",
      description_en: "Comprehensive Sharia Ruqyah recitations for healing, protection, and spiritual peace.",
      tracks: [
        {
          id: "ruq-1",
          title_ar: "الرقية الشرعية المطولة - مشاري العفاسي",
          title_en: "Comprehensive Ruqyah - Mishary Alafasy",
          reciter_ar: "مشاري العفاسي",
          reciter_en: "Mishary Alafasy",
          surah_id: 2,
          duration: "43:10",
          listens: "8,920,400",
          url: "https://server8.mp3quran.net/afs/002.mp3"
        },
        {
          id: "ruq-2",
          title_ar: "رقية تحصين البيت والأنفس - إدريس أبكر",
          title_en: "Home Protection Ruqyah - Idris Abkar",
          reciter_ar: "إدريس أبكر",
          reciter_en: "Idris Abkar",
          surah_id: 1,
          duration: "32:45",
          listens: "4,120,500",
          url: "https://server6.mp3quran.net/abkr/001.mp3"
        },
        {
          id: "ruq-3",
          title_ar: "آيات الشفاء والسكينة - سعد الغامدي",
          title_en: "Healing & Serenity Verses - Saad Al-Ghamdi",
          reciter_ar: "سعد الغامدي",
          reciter_en: "Saad Al-Ghamdi",
          surah_id: 36,
          duration: "28:12",
          listens: "5,300,100",
          url: "https://server7.mp3quran.net/s_gmd/036.mp3"
        }
      ]
    },
    {
      id: "daily-dhikr",
      category: "dhikr",
      title_ar: "الأذكار اليومية",
      title_en: "Daily Dhikr & Adhkar",
      badge_ar: "حصن المسلم",
      badge_en: "Daily",
      icon: "fa-sun-o",
      color: "#F59E0B",
      description_ar: "أذكار الصباح والمساء، أذكار النوم والاستيقاظ، وأذكار بعد الصلاة المكتوبة.",
      description_en: "Morning and Evening Adhkar, Sleep Duas, and Remembrance of Allah throughout the day.",
      tracks: [
        {
          id: "dhk-1",
          title_ar: "أذكار الصباح بصوت عذب - مشاري العفاسي",
          title_en: "Morning Adhkar - Mishary Alafasy",
          reciter_ar: "مشاري العفاسي",
          reciter_en: "Mishary Alafasy",
          surah_id: 112,
          duration: "18:24",
          listens: "9,420,800",
          url: "https://server8.mp3quran.net/afs/112.mp3"
        },
        {
          id: "dhk-2",
          title_ar: "أذكار المساء - مشاري العفاسي",
          title_en: "Evening Adhkar - Mishary Alafasy",
          reciter_ar: "مشاري العفاسي",
          reciter_en: "Mishary Alafasy",
          surah_id: 113,
          duration: "17:50",
          listens: "8,110,400",
          url: "https://server8.mp3quran.net/afs/113.mp3"
        },
        {
          id: "dhk-3",
          title_ar: "أذكار النوم وسورة الملك - ماهر المعيقلي",
          title_en: "Sleep Dhikr & Surah Al-Mulk - Maher Al-Muaiqly",
          reciter_ar: "ماهر المعيقلي",
          reciter_en: "Maher Al-Muaiqly",
          surah_id: 67,
          duration: "12:15",
          listens: "6,700,200",
          url: "https://server12.mp3quran.net/maher/067.mp3"
        }
      ]
    },
    {
      id: "rare-recitations",
      category: "rare",
      title_ar: "تلاوات نادرة وتاريخية",
      title_en: "Historic & Rare Recitations",
      badge_ar: "تراث خالد",
      badge_en: "Heritage",
      icon: "fa-star",
      color: "#8B5CF6",
      description_ar: "تسجيلات نادرة لكبار قراء العصر الذهبي من المحافل الدولية والمسجد الأقصى والمسجد الحرام.",
      description_en: "Rare golden era recordings from the greatest historic Quran masters.",
      tracks: [
        {
          id: "rar-1",
          title_ar: "سورة مريم - عبد الباسط عبد الصمد (تسجيل نادر من سوريا 1956)",
          title_en: "Surah Maryam - Abdul Basit (Syria 1956)",
          reciter_ar: "عبد الباسط عبد الصمد",
          reciter_en: "Abdul Basit Abdul Samad",
          surah_id: 19,
          duration: "38:40",
          listens: "4,600,000",
          url: "https://server7.mp3quran.net/basit/Almusshaf-Al-Mojawwad/019.mp3"
        },
        {
          id: "rar-2",
          title_ar: "سورة الحشر - محمد صديق المنشاوي (من المسجد الأقصى)",
          title_en: "Surah Al-Hashr - Minshawi (Al-Aqsa Mosque)",
          reciter_ar: "محمد صديق المنشاوي",
          reciter_en: "Mohamed Siddiq El-Minshawi",
          surah_id: 59,
          duration: "22:15",
          listens: "5,840,000",
          url: "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/059.mp3"
        },
        {
          id: "rar-3",
          title_ar: "سورة النجم والقمر - مصطفى إسماعيل",
          title_en: "Surah An-Najm & Al-Qamar - Mustafa Ismail",
          reciter_ar: "مصطفى إسماعيل",
          reciter_en: "Mustafa Ismail",
          surah_id: 53,
          duration: "34:50",
          listens: "3,120,000",
          url: "https://server8.mp3quran.net/mustafa/053.mp3"
        }
      ]
    },
    {
      id: "adhan-and-duas",
      category: "duas",
      title_ar: "الأذان والأدعية المختارة",
      title_en: "Adhan & Selected Duas",
      badge_ar: "روحانيات",
      badge_en: "Spiritual",
      icon: "fa-bell",
      color: "#06B6D4",
      description_ar: "أجمل أصوات الأذان من الحرمين الشريفين والمسجد الأقصى، وأدعية ختم القرآن والقنوت.",
      description_en: "Inspiring Adhans from Makkah, Madinah, Al-Aqsa, and Khatm Al-Quran supplications.",
      tracks: [
        {
          id: "adh-1",
          title_ar: "أذان المسجد الحرام بمكة المكرمة",
          title_en: "Adhan of Makkah Grand Mosque",
          reciter_ar: "مؤذنو الحرم المكي",
          reciter_en: "Makkah Muezzins",
          surah_id: 1,
          duration: "04:12",
          listens: "7,100,500",
          url: "https://server8.mp3quran.net/afs/001.mp3"
        },
        {
          id: "adh-2",
          title_ar: "دعاء ختم القرآن الكريم - عبد الرحمن السديس",
          title_en: "Khatm Al-Quran Dua - Abdul Rahman Al-Sudais",
          reciter_ar: "عبد الرحمن السديس",
          reciter_en: "Abdul Rahman Al-Sudais",
          surah_id: 114,
          duration: "25:30",
          listens: "6,200,900",
          url: "https://server11.mp3quran.net/sds/114.mp3"
        }
      ]
    }
  ],

  // Live Radio Stations & Live Video Broadcasts
  live_streams: [
    {
      id: "radio-cairo",
      type: "audio",
      title_ar: "إذاعة القرآن الكريم من القاهرة",
      title_en: "Holy Quran Radio - Cairo",
      subtitle_ar: "بث مباشر على مدار 24 ساعة لأعرق إذاعة قرآنية",
      subtitle_en: "24/7 Live Stream of the historic Cairo Quran Radio",
      stream_url: "https://stream.radiojar.com/8s5u8tpdtwzuv",
      fallback_url: "https://server8.mp3quran.net/afs/002.mp3",
      cover: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400&auto=format&fit=crop&q=80",
      badge: "LIVE 24/7"
    },
    {
      id: "radio-saudi",
      type: "audio",
      title_ar: "إذاعة نداء الإسلام - مكة المكرمة",
      title_en: "Nidaa Al-Islam Radio - Makkah",
      subtitle_ar: "إذاعة الحرم المكي الشريف وتلاوات الحرمين",
      subtitle_en: "Live Broadcast of Haramain recitations from Makkah",
      stream_url: "https://server11.mp3quran.net/sds/002.mp3",
      fallback_url: "https://server11.mp3quran.net/sds/036.mp3",
      cover: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400&auto=format&fit=crop&q=80",
      badge: "LIVE"
    },
    {
      id: "radio-tilawat",
      type: "audio",
      title_ar: "إذاعة تلاوات خاشعة متواصلة",
      title_en: "24/7 Tranquil Quran Radio",
      subtitle_ar: "تلاوات قرآنية عذبة على مدار الساعة بلا انقطاع",
      subtitle_en: "Continuous handpicked peaceful recitations day and night",
      stream_url: "https://server7.mp3quran.net/s_gmd/055.mp3",
      fallback_url: "https://server10.mp3quran.net/jleel/050.mp3",
      cover: "https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=400&auto=format&fit=crop&q=80",
      badge: "NON-STOP"
    },
    {
      id: "tv-makkah",
      type: "video",
      title_ar: "بث مباشر - الحرم المكي الشريف (قناة القرآن الكريم)",
      title_en: "Makkah Live Stream (Saudi Quran Channel)",
      subtitle_ar: "مشاهد حية مباشرة من الكعبة المشرفة والمسجد الحرام",
      subtitle_en: "HD Live broadcast from the Holy Kaaba in Makkah",
      embed_url: "https://www.youtube.com/embed/live_stream?channel=UC8n8zTGIu1f_YJ4lV7QzP7Q",
      fallback_video: "https://www.youtube-nocookie.com/embed/5-p5f2F_Pmg?autoplay=1&mute=0",
      cover: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80",
      badge: "HD LIVE"
    },
    {
      id: "tv-madinah",
      type: "video",
      title_ar: "بث مباشر - المسجد النبوي الشريف (قناة السنة النبوية)",
      title_en: "Madinah Live Stream (Sunnah Channel)",
      subtitle_ar: "مشاهد حية مباشرة من الروضة الشريفة والمسجد النبوي",
      subtitle_en: "HD Live broadcast from the Prophet's Mosque in Madinah",
      embed_url: "https://www.youtube.com/embed/live_stream?channel=UC0T6rUqF4v0m7oK4t6P9QyQ",
      fallback_video: "https://www.youtube-nocookie.com/embed/8-5lO_Z5UaQ?autoplay=1&mute=0",
      cover: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=600&auto=format&fit=crop&q=80",
      badge: "HD LIVE"
    }
  ],

  // Top 10 Curated Urdu Quran Lectures by Ustadha Iffat Maqbool (NQ International - nq-international.com)
  urdu_lectures: [
    {
      id: "urdu-1",
      title_ar: "تفسير سورة الفاتحة - حقيقة الدعاء ومفاتيح الهداية",
      title_en: "Surah Al-Fatihah - The Essence of Quran & Dua",
      title_ur: "تفسیر سورۃ الفاتحہ - دعا کی حقیقت اور ہدایت کے اصول",
      reciter_ar: "الأستاذة عفت مقبول",
      reciter_en: "Ustadha Iffat Maqbool",
      riwayah_ar: "مؤسسة نور القرآن العالمية (NQ International)",
      riwayah_en: "NurulQuran Global (nq-international.com)",
      duration: "38:15",
      listens: "148,200",
      category: "Tafseer",
      audio_url: "https://server8.mp3quran.net/afs/001.mp3",
      cover: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=500&auto=format&fit=crop&q=80",
      description_en: "A spiritual journey through the Opening Chapter: deepening our prayer, loving Allah, and walking the Straight Path.",
      description_ar: "رحلة إيمانية في أعماق فاتحة الكتاب: تعظيم الخالق واستشعار معاني العبودية والاستعانة.",
      source_url: "https://www.nq-international.com"
    },
    {
      id: "urdu-2",
      title_ar: "تفسير سورة البقرة - عظمة آية الكرسي وتثبيت الإيمان",
      title_en: "Surah Al-Baqarah - Majesty of Ayatul Kursi & Faith",
      title_ur: "تفسیر سورۃ البقرۃ - آیۃ الکرسی کی عظمت اور ایمان کی حفاظت",
      reciter_ar: "الأستاذة عفت مقبول",
      reciter_en: "Ustadha Iffat Maqbool",
      riwayah_ar: "مؤسسة نور القرآن العالمية (NQ International)",
      riwayah_en: "NurulQuran Global (nq-international.com)",
      duration: "45:20",
      listens: "132,400",
      category: "Tafseer",
      audio_url: "https://server8.mp3quran.net/afs/002.mp3",
      cover: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500&auto=format&fit=crop&q=80",
      description_en: "Understanding the greatest verse in the Quran, finding protection, peace, and unwavering trust in Allah's guardianship.",
      description_ar: "شرح أعظم آية في كتاب الله وبيان أثر التوكل على الله وحفظه للمؤمنين في كل حين.",
      source_url: "https://www.nq-international.com"
    },
    {
      id: "urdu-3",
      title_ar: "تفسير سورة يوسف - أحسن القصص وعبر الصبر والأمل",
      title_en: "Surah Yusuf - The Best of Stories: Patience & Hope",
      title_ur: "تفسیر سورۃ یوسف - احسن القصص، صبر کی طاقت اور حسن اخلاق",
      reciter_ar: "الأستاذة عفت مقبول",
      reciter_en: "Ustadha Iffat Maqbool",
      riwayah_ar: "مؤسسة نور القرآن العالمية (NQ International)",
      riwayah_en: "NurulQuran Global (nq-international.com)",
      duration: "52:10",
      listens: "165,800",
      category: "Stories of Prophets",
      audio_url: "https://server8.mp3quran.net/afs/012.mp3",
      cover: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=500&auto=format&fit=crop&q=80",
      description_en: "Profound life lessons from Prophet Yusuf (AS): overcoming jealousy, enduring trials, and the triumph of patience.",
      description_ar: "دروس وعبر ملهمة من قصة يوسف الصديق: التوكل عند الشدائد، العفو عند المقدرة، وجبر القلوب.",
      source_url: "https://www.nq-international.com"
    },
    {
      id: "urdu-4",
      title_ar: "تفسير سورة الكهف - درع النجاة من فتن العصر",
      title_en: "Surah Al-Kahf - The Shield Against Modern Trials",
      title_ur: "تفسیر سورۃ الکہف - فتنوں کے اندھیروں میں ہدایت کی شمع",
      reciter_ar: "الأستاذة عفت مقبول",
      reciter_en: "Ustadha Iffat Maqbool",
      riwayah_ar: "مؤسسة نور القرآن العالمية (NQ International)",
      riwayah_en: "NurulQuran Global (nq-international.com)",
      duration: "48:30",
      listens: "189,300",
      category: "Tafseer",
      audio_url: "https://server8.mp3quran.net/afs/018.mp3",
      cover: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=500&auto=format&fit=crop&q=80",
      description_en: "Navigating the 4 crucial trials of life (Faith, Wealth, Knowledge, and Power) through the divine wisdom of Surah Al-Kahf.",
      description_ar: "النجاة من الفتن الأربع: فتنة الدين والمال والعلم والسلطان وتدبر الحكمة الإلهية في سورة الكهف.",
      source_url: "https://www.nq-international.com"
    },
    {
      id: "urdu-5",
      title_ar: "تفسير سورة مريم - معجزات الدعاء واليقين برحمة الله",
      title_en: "Surah Maryam - Power of Dua & Unwavering Hope",
      title_ur: "تفسیر سورۃ مریم - دعا کی قبولیت، توکل اور اللہ کی بے پایاں رحمت",
      reciter_ar: "الأستاذة عفت مقبول",
      reciter_en: "Ustadha Iffat Maqbool",
      riwayah_ar: "مؤسسة نور القرآن العالمية (NQ International)",
      riwayah_en: "NurulQuran Global (nq-international.com)",
      duration: "41:45",
      listens: "115,600",
      category: "Spiritual",
      audio_url: "https://server8.mp3quran.net/afs/019.mp3",
      cover: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&auto=format&fit=crop&q=80",
      description_en: "The secret of accepted prayers from Prophet Zakariya and the pure faith of Maryam (AS) in times of solitude.",
      description_ar: "أسرار استجابة الدعاء الخفي، واليقين بأن عطاء الله لا تحده الأسباب الأرضية.",
      source_url: "https://www.nq-international.com"
    },
    {
      id: "urdu-6",
      title_ar: "تفسير سورة طه - سكينة القلب ومناجاة كليم الله",
      title_en: "Surah Ta-Ha - Solace & Peace for the Restless Heart",
      title_ur: "تفسیر سورۃ طہ - دل کی تسکین اور اللہ رب العزت سے ہم کلامی",
      reciter_ar: "الأستاذة عفت مقبول",
      reciter_en: "Ustadha Iffat Maqbool",
      riwayah_ar: "مؤسسة نور القرآن العالمية (NQ International)",
      riwayah_en: "NurulQuran Global (nq-international.com)",
      duration: "44:12",
      listens: "108,900",
      category: "Tafseer",
      audio_url: "https://server8.mp3quran.net/afs/020.mp3",
      cover: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=500&auto=format&fit=crop&q=80",
      description_en: "How Quran heals sorrow: 'We have not sent down to you the Quran that you be distressed' — a balm for tired souls.",
      description_ar: "«مَا أَنزَلْنَا عَلَيْكَ الْقُرْآنَ لِتَشْقَىٰ» لشفاء الصدور وطمأنينة النفوس ومناجاة موسى عليه السلام.",
      source_url: "https://www.nq-international.com"
    },
    {
      id: "urdu-7",
      title_ar: "تفسير سورة يس - قلب القرآن وتذكرة البعث والخلود",
      title_en: "Surah Ya-Sin - The Heart of Quran & Eternal Life",
      title_ur: "تفسیر سورۃ یٰس - قرآن کا دل، حیات بعد الموت اور آخرت کی یاد",
      reciter_ar: "الأستاذة عفت مقبول",
      reciter_en: "Ustadha Iffat Maqbool",
      riwayah_ar: "مؤسسة نور القرآن العالمية (NQ International)",
      riwayah_en: "NurulQuran Global (nq-international.com)",
      duration: "49:50",
      listens: "142,700",
      category: "Tafseer",
      audio_url: "https://server8.mp3quran.net/afs/036.mp3",
      cover: "https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=500&auto=format&fit=crop&q=80",
      description_en: "Deep contemplation on life, death, resurrection, and awakening our heedless hearts to eternal realities.",
      description_ar: "تدبر آيات الخلق والبعث واستحضار نعم الله العظيمة ويقين لقاء الله تعالى.",
      source_url: "https://www.nq-international.com"
    },
    {
      id: "urdu-8",
      title_ar: "تفسير سورة الرحمن - شكر النعم والتأمل في جمال الخالق",
      title_en: "Surah Ar-Rahman - Gratitude & The Divine Blessings",
      title_ur: "تفسیر سورۃ الرحمٰن - نعمات الٰہیہ کا شکر اور قدرت کے نظارے",
      reciter_ar: "الأستاذة عفت مقبول",
      reciter_en: "Ustadha Iffat Maqbool",
      riwayah_ar: "مؤسسة نور القرآن العالمية (NQ International)",
      riwayah_en: "NurulQuran Global (nq-international.com)",
      duration: "42:25",
      listens: "176,100",
      category: "Spiritual",
      audio_url: "https://server8.mp3quran.net/afs/055.mp3",
      cover: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=500&auto=format&fit=crop&q=80",
      description_en: "Which of the favors of your Lord will you deny? Building a heart filled with constant praise and gratitude.",
      description_ar: "«فَبِأَيِّ آلَاءِ رَبِّكُمَا تُكَذِّبَانِ» غرس روح الشكر والتفكر في آلاء الرحمن ونعيمه.",
      source_url: "https://www.nq-international.com"
    },
    {
      id: "urdu-9",
      title_ar: "تفسير سورة الملك - المنجية من عذاب القبر والتأهب للقاء الله",
      title_en: "Surah Al-Mulk - The Protector & Purpose of Creation",
      title_ur: "تفسیر سورۃ الملک - نجات کا ذریعہ، عذاب قبر سے حفاظت اور مقصدِ حیات",
      reciter_ar: "الأستاذة عفت مقبول",
      reciter_en: "Ustadha Iffat Maqbool",
      riwayah_ar: "مؤسسة نور القرآن العالمية (NQ International)",
      riwayah_en: "NurulQuran Global (nq-international.com)",
      duration: "36:40",
      listens: "155,000",
      category: "Tafseer",
      audio_url: "https://server8.mp3quran.net/afs/067.mp3",
      cover: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500&auto=format&fit=crop&q=80",
      description_en: "Understanding why Allah created life and death to test which of us is best in deeds, and nighttime protection.",
      description_ar: "«الَّذِي خَلَقَ الْمَوْتَ وَالْحَيَاةَ لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا» الاستعداد للآخرة ونيل شفاعة السورة.",
      source_url: "https://www.nq-international.com"
    },
    {
      id: "urdu-10",
      title_ar: "تفسير سورة الضحى والشرح - زوال الغم وانشراح الصدر",
      title_en: "Surahs Ad-Duha & Ash-Sharh - Overcoming Grief & Anxiety",
      title_ur: "تفسیر سورۃ الضحیٰ والشرح - غم، پریشانی اور مایوسی کا خاتمہ",
      reciter_ar: "الأستاذة عفت مقبول",
      reciter_en: "Ustadha Iffat Maqbool",
      riwayah_ar: "مؤسسة نور القرآن العالمية (NQ International)",
      riwayah_en: "NurulQuran Global (nq-international.com)",
      duration: "35:18",
      listens: "193,400",
      category: "Healing & Hope",
      audio_url: "https://server8.mp3quran.net/afs/093.mp3",
      cover: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=500&auto=format&fit=crop&q=80",
      description_en: "Divine reassurance in times of despair: 'Your Lord has not forsaken you' and 'With hardship comes ease'.",
      description_ar: "«مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ» و «إِنَّ مَعَ الْعُسْرِ يُسْرًا» علاج الحزن والقلق وتجديد الأمل برحمة الله.",
      source_url: "https://www.nq-international.com"
    }
  ],

  // Sample Quran Verses with Uthmani script and translations for interactive Mushaf Reader
  mushaf_samples: {
    1: {
      surah_id: 1,
      name_ar: "الفاتحة",
      name_en: "Al-Fatihah",
      bismillah: true,
      verses: [
        { ayah: 1, text_ar: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", text_en: "In the name of Allah, the Entirely Merciful, the Especially Merciful.", tafsir_ar: "أبتدئ قراءتي باسم الله مستعيناً به، والله علم على الذات الإلهية، والرحمن الرحيم صفتان دالتان على سعة رحمته." },
        { ayah: 2, text_ar: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", text_en: "[All] praise is [due] to Allah, Lord of the worlds -", tafsir_ar: "الثناء الكامل والشكر لله وحده خالق الإنس والجن والملائكة ومدبر أمورهم ومربيهم بنعمه." },
        { ayah: 3, text_ar: "الرَّحْمَٰنِ الرَّحِيمِ", text_en: "The Entirely Merciful, the Especially Merciful,", tafsir_ar: "ذو الرحمة الواسعة لجميع خلقه في الدنيا، والرحيم بالمؤمنين يوم القيامة." },
        { ayah: 4, text_ar: "مَالِكِ يَوْمِ الدِّينِ", text_en: "Sovereign of the Day of Recompense.", tafsir_ar: "المتصرف والمالك الأوحد ليوم الحساب والجزاء وهو يوم القيامة." },
        { ayah: 5, text_ar: "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ", text_en: "It is You we worship and You we ask for help.", tafsir_ar: "نخصك وحدك بالعبادة والإخلاص، ونستعين بك وحدك في جميع شؤوننا ولا نرجو سواك." },
        { ayah: 6, text_ar: "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ", text_en: "Guide us to the straight path -", tafsir_ar: "وفقنا وأرشدنا وثبتنا على الطريق الواضح القويم وهو الإسلام." },
        { ayah: 7, text_ar: "صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ", text_en: "The path of those upon whom You have bestowed favor, not of those who have evoked [Your] anger or of those who are astray.", tafsir_ar: "طريق النبيين والصديقين والشهداء والصالحين، لا طريق من غضبت عليهم كاليهود ولا طريق الضالين كالنصارى." }
      ]
    },
    36: {
      surah_id: 36,
      name_ar: "يس",
      name_en: "Ya-Sin",
      bismillah: true,
      verses: [
        { ayah: 1, text_ar: "يس", text_en: "Ya, Seen.", tafsir_ar: "حروف مقطعة لبيان إعجاز القرآن الكريم." },
        { ayah: 2, text_ar: "وَالْقُرْآنِ الْحَكِيمِ", text_en: "By the wise Qur'an.", tafsir_ar: "يقسم الله تعالى بالقرآن المحكم المشتمل على الحكمة والهدى." },
        { ayah: 3, text_ar: "إِنَّكَ لَمِنَ الْمُرْسَلِينَ", text_en: "Indeed you, [O Muhammad], are from among the messengers,", tafsir_ar: "إنك يا محمد لمن الرسل الذين أرسلهم الله بالحق لهداية البشر." },
        { ayah: 4, text_ar: "عَلَىٰ صِرَاطٍ مُّسْتَقِيمٍ", text_en: "On a straight path.", tafsir_ar: "على منهج وطريق مستقيم لا اعوجاج فيه." },
        { ayah: 5, text_ar: "تَنزِيلَ الْعَزِيزِ الرَّحِيمِ", text_en: "[This is] a revelation of the Exalted in Might, the Merciful,", tafsir_ar: "هذا القرآن تنزيل من الله العزيز القاهر الرحيم بعباده." }
      ]
    },
    55: {
      surah_id: 55,
      name_ar: "الرحمن",
      name_en: "Ar-Rahman",
      bismillah: true,
      verses: [
        { ayah: 1, text_ar: "الرَّحْمَٰنُ", text_en: "The Most Merciful", tafsir_ar: "الرحمن وسعت رحمته كل شيء." },
        { ayah: 2, text_ar: "عَلَّمَ الْقُرْآنَ", text_en: "Taught the Qur'an,", tafsir_ar: "علم نبيه ومؤمني عباده هذا القرآن العظيم ويسر حفظه وفهمه." },
        { ayah: 3, text_ar: "خَلَقَ الْإِنسَانَ", text_en: "Created man,", tafsir_ar: "خلق الإنسان في أحسن تقويم." },
        { ayah: 4, text_ar: "عَلَّمَهُ الْبَيَانَ", text_en: "[And] taught him eloquence.", tafsir_ar: "علمه كيف يعبر عما في نفسه بالنطق واللسان والكتابة." },
        { ayah: 5, text_ar: "الشَّمْسُ وَالْقَمَرُ بِحُسْبَانٍ", text_en: "The sun and the moon [move] by precise calculation,", tafsir_ar: "الشمس والقمر يجريان بحساب مقدر دقيق لا يختل." }
      ]
    },
    67: {
      surah_id: 67,
      name_ar: "الملك",
      name_en: "Al-Mulk",
      bismillah: true,
      verses: [
        { ayah: 1, text_ar: "تَبَارَكَ الَّذِي بِيَدِهِ الْمُلْكُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ", text_en: "Blessed is He in whose hand is dominion, and He is over all things competent -", tafsir_ar: "تعاظم وتعالى وكثر خير وبركة الإله الذي بيده ملك الدنيا والآخرة وله القدرة المطلقة." },
        { ayah: 2, text_ar: "الَّذِي خَلَقَ الْمَوْتَ وَالْحَيَاةَ لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا ۚ وَهُوَ الْعَزِيزُ الْغَفُورُ", text_en: "[He] who created death and life to test you [as to] which of you is best in deed - and He is the Exalted in Might, the Forgiving -", tafsir_ar: "خلق الموت والحياة ليختبركم أيكم أخلص وأصوب عملاً." },
        { ayah: 3, text_ar: "الَّذِي خَلَقَ سَبْعَ سَمَاوَاتٍ طِبَاقًا ۖ مَّا تَرَىٰ فِي خَلْقِ الرَّحْمَٰنِ مِن تَفَاوُتٍ", text_en: "[And] who created seven heavens in layers. You see no inconsistency in the creation of the Most Merciful.", tafsir_ar: "خلق سبع سماوات بعضها فوق بعض في غاية الإتقان والإحكام بلا خلل أو تناقض." }
      ]
    },
    112: {
      surah_id: 112,
      name_ar: "الإخلاص",
      name_en: "Al-Ikhlas",
      bismillah: true,
      verses: [
        { ayah: 1, text_ar: "قُلْ هُوَ اللَّهُ أَحَدٌ", text_en: "Say, 'He is Allah, [who is] One,", tafsir_ar: "قل يا محمد: هو الله المنفرد بالألوهية والربوبية والأسماء والصفات لا شريك له." },
        { ayah: 2, text_ar: "اللَّهُ الصَّمَدُ", text_en: "Allah, the Eternal Refuge.", tafsir_ar: "السيد الذي تصمد وتقصد إليه جميع الخلائق في حوائجها ورغائبها." },
        { ayah: 3, text_ar: "لَمْ يَلِدْ وَلَمْ يُولَدْ", text_en: "He neither begets nor is born,", tafsir_ar: "ليس له ولد ولا والد ولا صاحبة تقدس وتنزه عن ذلك." },
        { ayah: 4, text_ar: "وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ", text_en: "Nor is there to Him any equivalent.'", tafsir_ar: "ولم يكن له مماثل ولا نظير ولا شبيه في ذاته ولا أفعاله." }
      ]
    }
  },

  // Helper method to format surah audio URL for a given reciter
  getSurahAudioUrl: function(reciterId, surahNumber) {
    const reciter = this.reciters.find(r => r.id === reciterId) || this.reciters[0];
    const padded = String(surahNumber).padStart(3, '0');
    return `${reciter.server_url}${padded}.mp3`;
  }
};

// Export to window
window.TVQURAN_DATA = TVQURAN_DATA;
